/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    GameBoard: typeof import('./src/components/Game/GameBoard.vue')['default']
    GameKeyboard: typeof import('./src/components/Game/GameKeyboard.vue')['default']
    GameTile: typeof import('./src/components/Game/GameTile.vue')['default']
  }
}
